<?php

/**
 * Implements hook_entity_info().
 */
function libhours_entity_info() {
  $info = array();
  $info['libhours_period'] = array(
    'label' => t('Period'),
    'fieldable' => FALSE,
    'entity class' => 'Entity',
    'controller class' => 'LibhoursPeriodController',
    'base table' => 'libhours_period',
    'entity keys' => array(
      'id' => 'period_id',
    ),
  );

  $info['libhours_schedule'] = array(
    'label' => t('Schedule'),
    'fieldable' => TRUE,
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIController',
    'base table' => 'libhours_schedule',
    'entity keys' => array(
      'id' => 'schedule_id',
    ),
    'bundles' => array(
      'schedule_bundle' => array(
        'label' => 'Schedule',
      ),
    ),
  );

  return $info;
}

/**
 * Implements hook_field_info().
 */
function libhours_field_info() {
  return array(
    'libhours_shift' => array(
      'label' => t('Shift'),
      'description' => t("This field stores Shifts."),
      'settings' => array('allowed_values' => array(), 'allowed_values_function' => ''),
      'default_widget' => 'libhours_shift',
      'default_formatter' => 'libhours_shift',
      'property_type' => 'libhours_shift',
      //'property_callbacks' => array('libhours_shift_property_info_callback'),
    ),
  );  
}

/**
 * Implements hook_menu().
 */
function libhours_menu() {
  $items = array();
  $items['period/%'] = array(
    'title' => 'Periods',
    'page callback' => '_libhours_view_period',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Callback function for displaying a Period
 */
function _libhours_view_period($id) {
  // entity_load returns array
  $periods = entity_load('libhours_period', array($id));
  $period = $periods[$id];
  drupal_set_title($period->period_name);

  return entity_view('libhours_period', array($period));
}

/**
 * Convenience function for saving a Period.
 */
function _libhours_save_period($period) {
  entity_save('libhours_period', $period);
}


function libhours_shift_property_info_callback() {
}

