#!/bin/sh

if [ -z "$1" ]; then
  echo testit on\|off
  exit 1
fi

case $1 in
  on)
    drush @bs en -y libhours_demo
    drush @bs sqlq "show tables like '%libhours%'"
    drush @bs sqlq "select * from libhours_period"
    drush @bs sqlq "select * from libhours_schedule"
    ;;
  off)
    drush @bs dis -y libhours_demo libhours
    drush @bs pmu -y libhours_demo
    drush @bs pmu -y libhours
    drush @bs sqlq "show tables like '%libhours%'"
    ;;
esac

drush @bs cc all

